colormap = {
    "pdf": "red",
    "ppt": "bright_red",
    "pptx": "bright_red",
    "vnd.openxmlformats-officedocument.presentationml.presentation": "bright_red",
    "image": "green",
    "doc": "blue",
    "vnd.openxmlformats-officedocument.wordprocessingml.document": "blue",
    "x-script.python": "bright_cyan",
    "json": "yellow",
    "javascript": "yellow",
    "audio": "cyan",
    "video": "magenta",
    "plain": "white",
    "csv": "bright_green",
    "vnd.openxmlformats-officedocument.spreadsheetml.sheet": "green",
    "zip": "bright_blue",
    "exe": "bright_red",
}

MIME_TYPE_ICONS = {
    "pdf": "📄",
    "ppt": "📊",
    "pptx": "📊",
    "vnd.openxmlformats-officedocument.presentationml.presentation": "📊",
    "image": "🖼️",
    "doc": "📃",
    "vnd.openxmlformats-officedocument.wordprocessingml.document": "📃",
    "json": "🔧",
    "audio": "🎵",
    "video": "🎬",
    "text": "📄",
    "x-script.python": "🐍",
    "javascript": "📜",
    "csv": "📈",
    "vnd.openxmlformats-officedocument.spreadsheetml.sheet": "📈",
    "zip": "🗜️",
    "exe": "⚙️",
}
